target 'SkillTest' do
platform :ios, '9.0'
use_frameworks!

# Pods for SkillTest
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'SnapKit',    '~> 4.0.0'
    pod 'NVActivityIndicatorView'
end

target ‘SkillTestTests’ do
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'SnapKit',    '~> 4.0.0'
    pod 'NVActivityIndicatorView'
end

target ‘SkillTestUITests’ do
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Kingfisher', '~> 4.0'
    pod 'SnapKit',    '~> 4.0.0'
    pod 'NVActivityIndicatorView'
end